### ISSUE TITLE
[BUG] Create token function fails when using Vision 5E due to `Detection Mode - Light Perception - Infinity` setting.

### ISSUE THREAD

**Issue by Tatonker** [ironmonk88/monks-active-tiles#569]
**Describe the bug**
 I had a working tile that when clicked would hide itself and create a Mimic token in its place (a mimic chest). As soon as I enable V5E the tile triggers up to the point of creating the token then throws a UI error and the following console error:
```js
foundry.js:753  Error: TokenDocument5e validation errors:
  detectionModes: 
    0: 
      range: must be a finite number
    at DataModelValidationFailure.asError (commons.js:3805:14)
    at TokenDocument5e.validate (commons.js:7070:61)
    at new DataModel (commons.js:6824:12)
    at new Document (commons.js:7489:3)
    at new BaseToken (commons.js:12168:3)
    at new ClientDocumentMixin (foundry.js:13894:7)
    at new CanvasDocument (foundry.js:13228:10)
    at new TokenDocument (foundry.js:24710:1)
    at new TokenDocument5e (token.mjs:6:16)
    at new TokenDocument5e (automation.mjs:138:34)
    at #preCreateDocumentArray (foundry.js:13450:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:13343:73)
    at ClientDatabaseBackend.create (commons.js:8535:19)
    at async TokenDocument5e.createDocuments (commons.js:7864:23)
    at async Promise.all (index 0)
    at async TileDocument.fn (actions.js:1293:38)
    at async TileDocument.runActions (monks-active-tiles.js:4034:56)
```
I've noticed that the Mimic in question (DDB import version) has a Detection Mode - Light Percption = Infinity which could be the problem. With V5E disabled it works properly, as soon as V5E is enabled it throws that error. Anyone else seen weird things like this? Dragging the actor from the sidebar works, so it is something going on with the creation event in MATT. Anyone have any ideas?

**To Reproduce**
1. Create a tile with 'Click' activation and 'Create Token' action.
2. Trigger the tile and the tile throws an error per above.

**Expected behavior**
The tile works as expected without V5E being enabled, but V5E creates a `Light Perception = Infinity` which appears to not be accepted by the `Create Token` function.

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/70360365/fe53affe-65a7-418b-a516-829a90e4bfa6)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/70360365/fac94716-3aaf-4b6c-aa38-99eb776b9ebb)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 11.306
 - System D&D5e 2.2.2
 - Module version 11.02
 - Are there any errors in the console [e.g. press F12 and look for red text] - See above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No

**Additional context**
With a manually added 'Light Perception' with a finite number (second image attached) the tile completes the action properly. Please see short conversation on the MATT discord channel for additional context but it comes down to V5E needing to use an infinite number to account for the different needs of users on different maps / grid counts and manually adding a Light Perception detection mode to every actor in a compendium / world would be highly time-consuming. 

Can the Create Token function be adjusted to accept an `Infinte` value in the Detection Mode?

https://discord.com/channels/862414864692281386/862421211749154816/1136733634603270235

**Comment by Tatonker** [comment]
Per the author of Vision 5E on his Github issue I created.

I suspect MATT creates the token from the prepared data instead of the source data (.toObject(false) instead of .toObject(true)).

**Comment by ironmonk88** [comment]
I am unable to replicate this.
MATT uses `actor.getTokenDocument()` which in the foundry code returns the source data, so that's not the issue.
I tried replicating using the values you provided and there were no errors, created as expected.
Does that character fail in any other worlds?
Or try exporting the actor and uploading here and I'll try importing in my code and see if it still fails.
