### ISSUE TITLE
[BUG] New Update Broke Teleport Function

### ISSUE THREAD

**Issue by GorodZolotoy** [ironmonk88/monks-active-tiles#604]
**Describe the bug**
Tokens are no longer able to teleport to other scenes after the recent update. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create teleport tile by using double click and the teleport function
2. Click on the tile

**Expected behavior**
Teleport token.

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version v11.308
 - PF2E
 - Module version 11.08
 - browser error text:
 monks-active-tiles |  TypeError: dests.pickRandom is not a function
    at _TileDocumentPF2e.fn (actions.js:310:42)
    at async TileDocument.runActions (monks-active-tiles.js:4213:52)
    at async TileDocument.trigger (monks-active-tiles.js:4164:36)

**Additional context**

**Comment by GorodZolotoy** [comment]
The issue has been fixed as of module version 11.09
