### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by DalishRanger** [ironmonk88/monks-active-tiles#715]
**Describe the bug**
When both Window Controls and Monk's Active Tile Triggers are active, any tiles that use an onClick or Double onClick function do not work. On Enter and other tiles seem to work fine, but if you use MATT for things like menus, DM buttons and such, they won't work while Windows Controls is active. This happens regardless of permission (GM only, Players, all, etc) and as far as I've found, regardless of action (Open Journal, Show notification, execute a macro, etc). 

Sometimes after initially opening a world, the tile action will work once, but not a second or more time.

I'm not sure which mod, if not both, need to be tweaked for them not to conflict, but I'm reporting it for both modules just in case.

**To Reproduce**
1. With Window Controls deactivated, create a tile with a click or double click trigger.
2. Give the tile an action, such as a notification.
3. Test the button, it should work.
4. If the button works, activate Window Controls and repeat above steps. It may work once, but not again after.

**Expected behavior**
Both mods to be active and functioning as expected.

**Please complete as much of the following information as possible:**
 - Browsers: Foundry software, Chrome, FireFox
 - Foundry Version: 11
 - System: D&D5e
 - Module version: 11.21
 - Are there any errors in the console Yes, 3 but all say the same thing, "TypeError: An error occurred while rendering ControlManager 13. Cannot set properties of undefined (setting 'active')
[Detected 1 package: lib-df-buttons]
    at ControlManager.getData (ControlManager.ts:168:15)
    at async ControlManager._render (foundry.js:5812:18)
    at async ControlManager._render (ControlManager.ts:263:3)"
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: It is a module interaction, but as far as I know they shouldn't be conflicting with each other - I could be wrong though, they may interact with similar areas of the canvas.

**Comment by Crowguard** [comment]
Also cannot replicate this.

**Comment by yorkshirelandscape** [comment]
I can confirm this one. The tiles have to be under 200x200 in size for it to happen. 100x100 will never work, some sizes in between will work, and 200x200 will always work.

**Comment by DalishRanger** [comment]
> I can confirm this one. The tiles have to be under 200x200 in size for it to happen. 100x100 will never work, some sizes in between will work, and 200x200 will always work.

Most of my tiles are small activation buttons, so this would correlate with my experience. I had to disable Windows Controls to get the tiles working at all again.
