### ISSUE TITLE
[BUG] Auto Roll with Bypass Dialog not working with Active Tiles Request Roll

### ISSUE THREAD

**Issue by BadNerdCreating** [ironmonk88/monks-active-tiles#859]
![Screenshot 2024-10-22 014015](https://github.com/user-attachments/assets/78815082-9684-4480-bd82-834b9865e68b)

![Screenshot 2024-10-22 014056](https://github.com/user-attachments/assets/d3dfcbb2-b157-457e-a966-76df23ebd451)

 - Browser Chrome
 - Foundry Version v12 stable - 331
 - System DnD 5e v.4.0.4
 - Monks Active Tile Triggers v12.02 & Monks Token Bar v12.02
 - console errors:
 dnd5e-rolls.js:203 TypeError: Cannot read properties of undefined (reading 'closest')
    at d20Roll (dice.mjs:125:34)
    at async Actor5e.rollSkill (actor.mjs:1417:18)
    at async Promise.all (index 0)
 
 - I have tried Find the Culprit. It didn't give me anything useful. 

- Bypass Dialog and Auto Roll both work when used one or the other. They are not working together. 
i did try changing the rolls between public roll and gm roll and everything in between. I got the same results.

**Comment by Crowguard** [comment]
Anything involving Tokenbar should be logged with Tokenbar, not MATT, and this is a duplicate of https://github.com/ironmonk88/monks-tokenbar/issues/487.

**Comment by BadNerdCreating** [comment]
> Anything involving Tokenbar should be logged with Tokenbar, not MATT, and this is a duplicate of [ironmonk88/monks-tokenbar#487](https://github.com/ironmonk88/monks-tokenbar/issues/487).

Okay I wasn't sure because roll requests within token bar work it's only when it's used together with active tiles.

**Comment by TheAlexPlus** [comment]
I am having this same issue where a bunch of my tiles aren't auto rolling.

Oddly enough, I created an empty tile and added only the roll action and it worked.
I tested a few things and it seems like if the tile has received its token collection from another tile it doesn't work, but if the collection was set internally it does work.
